"""add_metadata_to_chatmessage

Revision ID: 65206900a940
Revises: 9f45bd1c84a3
Create Date: 2026-04-03 22:58:53.304125

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '65206900a940'
down_revision = '9f45bd1c84a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatmessage', 'metadata')
    # ### end Alembic commands ###
