"""add source and conversation_id to taskjob

Revision ID: 9f45bd1c84a3
Revises: 9c19ad76e387
Create Date: 2026-03-21 17:53:35.744102

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9f45bd1c84a3'
down_revision = '9c19ad76e387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskjob', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='manual'))
    op.add_column('taskjob', sa.Column('conversation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_taskjob_conversation_id'), 'taskjob', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'taskjob', 'conversation', ['conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taskjob', type_='foreignkey')
    op.drop_index(op.f('ix_taskjob_conversation_id'), table_name='taskjob')
    op.drop_column('taskjob', 'conversation_id')
    op.drop_column('taskjob', 'source')
    # ### end Alembic commands ###
