/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTasksRouteImport } from './routes/_layout/tasks'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMoleculeEditorRouteImport } from './routes/_layout/molecule-editor'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutTasksIndexRouteImport } from './routes/_layout/tasks/index'
import { Route as LayoutChatIndexRouteImport } from './routes/_layout/chat/index'
import { Route as LayoutTasksTaskIdRouteImport } from './routes/_layout/tasks/$taskId'
import { Route as LayoutChatConversationIdRouteImport } from './routes/_layout/chat/$conversationId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksRoute = LayoutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoleculeEditorRoute = LayoutMoleculeEditorRouteImport.update({
  id: '/molecule-editor',
  path: '/molecule-editor',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksIndexRoute = LayoutTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTasksRoute,
} as any)
const LayoutChatIndexRoute = LayoutChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutChatRoute,
} as any)
const LayoutTasksTaskIdRoute = LayoutTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => LayoutTasksRoute,
} as any)
const LayoutChatConversationIdRoute =
  LayoutChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => LayoutChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRouteWithChildren
  '/molecule-editor': typeof LayoutMoleculeEditorRoute
  '/settings': typeof LayoutSettingsRoute
  '/tasks': typeof LayoutTasksRouteWithChildren
  '/chat/$conversationId': typeof LayoutChatConversationIdRoute
  '/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/chat/': typeof LayoutChatIndexRoute
  '/tasks/': typeof LayoutTasksIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/molecule-editor': typeof LayoutMoleculeEditorRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/chat/$conversationId': typeof LayoutChatConversationIdRoute
  '/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/chat': typeof LayoutChatIndexRoute
  '/tasks': typeof LayoutTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/chat': typeof LayoutChatRouteWithChildren
  '/_layout/molecule-editor': typeof LayoutMoleculeEditorRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tasks': typeof LayoutTasksRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/chat/$conversationId': typeof LayoutChatConversationIdRoute
  '/_layout/tasks/$taskId': typeof LayoutTasksTaskIdRoute
  '/_layout/chat/': typeof LayoutChatIndexRoute
  '/_layout/tasks/': typeof LayoutTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/molecule-editor'
    | '/settings'
    | '/tasks'
    | '/chat/$conversationId'
    | '/tasks/$taskId'
    | '/chat/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/molecule-editor'
    | '/settings'
    | '/'
    | '/chat/$conversationId'
    | '/tasks/$taskId'
    | '/chat'
    | '/tasks'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/chat'
    | '/_layout/molecule-editor'
    | '/_layout/settings'
    | '/_layout/tasks'
    | '/_layout/'
    | '/_layout/chat/$conversationId'
    | '/_layout/tasks/$taskId'
    | '/_layout/chat/'
    | '/_layout/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks': {
      id: '/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/molecule-editor': {
      id: '/_layout/molecule-editor'
      path: '/molecule-editor'
      fullPath: '/molecule-editor'
      preLoaderRoute: typeof LayoutMoleculeEditorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/': {
      id: '/_layout/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof LayoutTasksIndexRouteImport
      parentRoute: typeof LayoutTasksRoute
    }
    '/_layout/chat/': {
      id: '/_layout/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof LayoutChatIndexRouteImport
      parentRoute: typeof LayoutChatRoute
    }
    '/_layout/tasks/$taskId': {
      id: '/_layout/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof LayoutTasksTaskIdRouteImport
      parentRoute: typeof LayoutTasksRoute
    }
    '/_layout/chat/$conversationId': {
      id: '/_layout/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof LayoutChatConversationIdRouteImport
      parentRoute: typeof LayoutChatRoute
    }
  }
}

interface LayoutChatRouteChildren {
  LayoutChatConversationIdRoute: typeof LayoutChatConversationIdRoute
  LayoutChatIndexRoute: typeof LayoutChatIndexRoute
}

const LayoutChatRouteChildren: LayoutChatRouteChildren = {
  LayoutChatConversationIdRoute: LayoutChatConversationIdRoute,
  LayoutChatIndexRoute: LayoutChatIndexRoute,
}

const LayoutChatRouteWithChildren = LayoutChatRoute._addFileChildren(
  LayoutChatRouteChildren,
)

interface LayoutTasksRouteChildren {
  LayoutTasksTaskIdRoute: typeof LayoutTasksTaskIdRoute
  LayoutTasksIndexRoute: typeof LayoutTasksIndexRoute
}

const LayoutTasksRouteChildren: LayoutTasksRouteChildren = {
  LayoutTasksTaskIdRoute: LayoutTasksTaskIdRoute,
  LayoutTasksIndexRoute: LayoutTasksIndexRoute,
}

const LayoutTasksRouteWithChildren = LayoutTasksRoute._addFileChildren(
  LayoutTasksRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutChatRoute: typeof LayoutChatRouteWithChildren
  LayoutMoleculeEditorRoute: typeof LayoutMoleculeEditorRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTasksRoute: typeof LayoutTasksRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutChatRoute: LayoutChatRouteWithChildren,
  LayoutMoleculeEditorRoute: LayoutMoleculeEditorRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTasksRoute: LayoutTasksRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
